feign:
  name: currency
  url: https://api.exchangeratesapi.io/latest
  httpclient:
    disable-ssl-validation: true
    enabled: false
  okhttp:
    enabled: true

currency:
  base: "EUR"

server:
  port: 9090

